### ISSUE TITLE
Question on the roadmap of bpf-api

### ISSUE THREAD

**Issue by BobAnkh** [arcjustin/bpf-api#5]
Hey, arcjustin, I have noticed your projects on bpf about a week ago, really a rapid development progress.

I would like to pick a rust ebpf library to write programs. I appreciate the motivation behind your bpf crates of having a fully Rust eBPF solution. Thus I would like to know more on your project, including the current status and future roadmap.

What is the difference of your project compared to aya-rs(another fully rust ebpf solution) or redbpf(a famous crate based on libbpf)? aya-rs and redbpf does not support all kinds of bpf program type and libbpf(libbpf-sys/libbpf-rs) seems hard to be written in pure rust.

**Comment by arcjustin** [comment]
Hey, at this time, this is more of a personal project that I've thrown together, primarily for learning. If you're looking for something more reliable and better maintained, I would go with `aya`.

I'm primarily a Linux kernel developer, and wrote all of this implementation by referencing kernel internals; I haven't used or looked too much at any other eBPF crates so I'm not 100% sure of the differences. However, here are some of my goals:

1. Create small, individual crates with minimal dependencies each with a single, logical BPF-related purpose. For example, `btf` and `btf-ins` are both self-contained crates that are small and useful on their own.
2. Have no external dependencies;  I believe other crates require certain libraries, like libbpf, or programs, like bcc, installed on the machine to function. Using this crate along with the others requires no external programs or libraries.
3. Create a small scripting language that can compile to eBPF at runtime (bpf-script); this one was inspired by the Python examples in bcc - I thought to myself, "I want to have the same thing in Rust: have a string representation of my eBPF program right where it's loaded. But I dont want to shell out to bcc and load it."

As for the roadmap: I've been setting top-level goals and developing the individual crates towards them. The first milestone I hit was being able to trace user-space programs with uprobes (`user-tracer`). Since then, I've just been cleaning up code and fixing bugs. I'll be working on increasing reliability of the code that I currently have before implementing any new features in the near future.
